### ISSUE TITLE
Can't access on browser

### ISSUE THREAD

**Issue by stebiger** [ricardogarfe/sonarqube-puppet#1]
Hi Ricardo,

unfortunately I am not able to open sonarqube from my host using webbrowser.

I set up a private network instead of bridget for forwarded posts.

Anyhow, when I try to access on port 9000 browser seems to load infinetely.
Doing tcpdump on private network interface on guest there is also no traffic.

Do you have any idea what is wrong? I know this differs slightly from your original maintained configuration but maybe you have an idea.

Regards,
Stefan

**Comment by stebiger** [comment]
It was a company's own proxy which caused the issue.

**Comment by ricardogarfe** [comment]
Hi ! I couldn't see the comment at time :S But perfect that you fix it :+1:  
Thanks for the comment and regards!

Ricardo.
